ALTER TABLE planes_traslados ADD COLUMN estado TINYINT(1) DEFAULT 1;
ALTER TABLE movil ADD UNIQUE (num);
ALTER TABLE movil ADD UNIQUE (patente);
ALTER TABLE movil ADD COLUMN activo BOOL DEFAULT TRUE;
ALTER TABLE personal ADD COLUMN activo BOOL DEFAULT TRUE;